
WeakAurasSaved = {
["dynamicIconCache"] = {
},
["editor_tab_spaces"] = 2,
["editor_font_size"] = 12,
["features"] = {
},
["login_squelch_time"] = 10,
["lastArchiveClear"] = 1755696921,
["minimap"] = {
["minimapPos"] = 186.7832989727105,
["hide"] = true,
},
["historyCutoff"] = 730,
["dbVersion"] = 85,
["migrationCutoff"] = 730,
["registered"] = {
},
["displays"] = {
["회복탐"] = {
["iconSource"] = -1,
["xOffset"] = 0,
["preferToUpdate"] = false,
["customText"] = "function()\n    mana = math.max(0, UnitPower(\"player\", 0)) / math.max(1, UnitPowerMax(\"player\", 0)) * 100;\n    return string.format(\"%.0f\", mana);\nend",
["yOffset"] = -200,
["anchorPoint"] = "TOP",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = false,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["rem"] = "10",
["useGroup_count"] = false,
["matchesShowOn"] = "showOnActive",
["unit"] = "player",
["use_tooltip"] = false,
["debuffType"] = "HELPFUL",
["useName"] = true,
["use_debuffClass"] = false,
["subeventSuffix"] = "_CAST_START",
["event"] = "Health",
["subeventPrefix"] = "SPELL",
["type"] = "aura2",
["auranames"] = {
"음료",
"음식",
},
["spellIds"] = {
192002,
185710,
},
["buffShowOn"] = "showOnActive",
["remOperator"] = ">=",
["combineMatches"] = "showLowest",
["names"] = {
"Food & Drink",
"Sugar-Crusted Fish Feast",
},
["useRem"] = false,
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["animation"] = {
["start"] = {
["type"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["easeType"] = "none",
},
},
["stickyDuration"] = false,
["version"] = 1,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 48,
["selfPoint"] = "TOP",
["load"] = {
["talent2"] = {
["multi"] = {
},
},
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["difficulty"] = {
["multi"] = {
},
},
["role"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
},
},
["pvptalent"] = {
["multi"] = {
},
},
["race"] = {
["multi"] = {
},
},
["faction"] = {
["multi"] = {
},
},
["ingroup"] = {
["multi"] = {
},
},
["size"] = {
["single"] = "party",
["multi"] = {
["twenty"] = true,
["party"] = true,
},
},
},
["frameStrata"] = 1,
["useAdjustededMax"] = false,
["color"] = {
1,
1,
1,
1,
},
["source"] = "import",
["adjustedMin"] = "",
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["conditions"] = {
},
["adjustedMax"] = "",
["useAdjustededMin"] = false,
["regionType"] = "icon",
["progressSource"] = {
-1,
"",
},
["config"] = {
},
["authorOptions"] = {
},
["anchorFrameType"] = "SCREEN",
["cooldownTextDisabled"] = false,
["auto"] = true,
["zoom"] = 0,
["semver"] = "1.0.0",
["tocversion"] = 20501,
["id"] = "회복탐",
["useCooldownModRate"] = true,
["alpha"] = 1,
["width"] = 48,
["desaturate"] = false,
["uid"] = "(Vqa)He833C",
["inverse"] = false,
["actions"] = {
["start"] = {
["message_format_1.unit_abbreviate"] = false,
["message_format_percent_abbreviate"] = false,
["message_format_percent_abbreviate_max"] = 8,
["message_format_percentpower_abbreviate_max"] = 8,
["do_custom"] = false,
["message_format_1.spell_format"] = "none",
["message_format_1.unit_color"] = true,
["message_format_1.unit_format"] = "Unit",
["message"] = "▶  %1.n (%c) 탐 중...",
["message_format_n_format"] = "none",
["message_format_percentpower_format"] = "string",
["message_format_.1f_big_number_format"] = "AbbreviateNumbers",
["message_format_.1f_abbreviate"] = true,
["message_custom"] = "function()\n  mana = 0;\n  if UnitPowerMax(\"player\", 0) == 0 then\n    mana = math.max(0, UnitHealth(\"player\")) / math.max(1, UnitHealthMax(\"player\")) * 100;\n  else    \n    mana = math.max(0, UnitPower(\"player\", 0)) / math.max(1, UnitPowerMax(\"player\", 0)) * 100;\n  end\n  return string.format(\"%.0f%%\", mana);\nend",
["message_format_percentpower_color"] = true,
["do_message"] = true,
["message_format_1.unitpower_abbreviate_max"] = 8,
["message_format_1.spellId_format"] = "none",
["message_format_1.unit_abbreviate_max"] = 8,
["message_format_percent_format"] = "string",
["message_format_1.n_format"] = "none",
["message_format_percentpower_realm_name"] = "never",
["message_format_percentpower_abbreviate"] = false,
["message_format_1.unitpower_format"] = "none",
["message_format_c2_format"] = "none",
["message_format_1.unitpower_abbreviate"] = false,
["message_format_1.unitpower_realm_name"] = "never",
["message_format_c_format"] = "none",
["message_format_1.spellName_format"] = "none",
["message_format_.1f_format"] = "Unit",
["message_format_c1_format"] = "none",
["message_format_.1f_color"] = "class",
["custom"] = "SendChatMessage((\"Mana: %d%%\"):format(aura_env.state.percentpower))",
["message_type"] = "SMARTRAID",
["message_format_1.unitpower_color"] = true,
["message_format_.1f_realm_name"] = "star",
["message_format_1.unit_realm_name"] = "never",
["message_format_.1f_abbreviate_max"] = 20,
},
["init"] = {
["do_custom"] = false,
},
["finish"] = {
["message"] = "▶  %1.n (%c) 탐 완료.",
["message_custom"] = "function()\n  mana = 0;\n  if UnitPowerMax(\"player\", 0) == 0 then\n    mana = math.max(0, UnitHealth(\"player\")) / math.max(1, UnitHealthMax(\"player\")) * 100;\n  else    \n    mana = math.max(0, UnitPower(\"player\", 0)) / math.max(1, UnitPowerMax(\"player\", 0)) * 100;\n  end\n  return string.format(\"%.0f%%\", mana);\nend",
["message_type"] = "SMARTRAID",
["message_format_1.n_format"] = "none",
["do_message"] = true,
["message_format_c_format"] = "none",
},
},
["displayIcon"] = "",
["cooldown"] = true,
["url"] = "",
},
["ShieldIcon"] = {
["iconSource"] = -1,
["color"] = {
1,
1,
1,
1,
},
["adjustedMax"] = "",
["adjustedMin"] = "",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["cooldownEdge"] = false,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["rem"] = "0",
["auranames"] = {
"신의 권능: 보호막",
},
["names"] = {
},
["powertype"] = 1,
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
["showClones"] = false,
["useName"] = true,
["use_debuffClass"] = false,
["auraspellids"] = {
"27607",
"6788",
},
["event"] = "Power",
["use_unit"] = true,
["subeventPrefix"] = "SPELL",
["useExactSpellId"] = false,
["spellIds"] = {
},
["unit"] = "player",
["remOperator"] = ">=",
["subeventSuffix"] = "_CAST_START",
["type"] = "aura2",
["useRem"] = true,
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["class"] = "WARRIOR",
["use_requirePowerType"] = true,
["use_unit"] = true,
["use_class"] = false,
["powertype"] = 1,
["event"] = "Power",
["unit"] = "player",
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["text_shadowXOffset"] = 0,
["text_text_format_s_format"] = "none",
["text_text"] = "%p",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_legacy_floor"] = false,
["type"] = "subtext",
["text_text_format_p_time_dynamic_threshold"] = 60,
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "Friz Quadrata TT",
["text_text_format_p_format"] = "timed",
["text_shadowYOffset"] = 0,
["text_text_format_p_time_mod_rate"] = true,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_fontType"] = "OUTLINE",
["text_text_format_p_time_format"] = 0,
["anchor_point"] = "INNER_BOTTOMRIGHT",
["text_fontSize"] = 14,
["anchorXOffset"] = 0,
["text_text_format_p_time_precision"] = 1,
},
{
["glowFrequency"] = 0.25,
["type"] = "subglow",
["useGlowColor"] = false,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowScale"] = 1,
["glowThickness"] = 1,
["glowDuration"] = 1,
["glowXOffset"] = 0,
["glow"] = true,
["glowLines"] = 8,
["glowBorder"] = false,
},
},
["height"] = 64,
["load"] = {
["use_class"] = true,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["single"] = "WARRIOR",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["useAdjustededMax"] = false,
["parent"] = "신의권능: 보호막 (전사)",
["useAdjustededMin"] = false,
["regionType"] = "icon",
["displayIcon"] = 135940,
["xOffset"] = 0,
["progressSource"] = {
-1,
"",
},
["cooldown"] = true,
["actions"] = {
["start"] = {
["message_type"] = "WHISPER",
["do_message"] = false,
["message_dest"] = "",
},
["init"] = {
},
["finish"] = {
},
},
["config"] = {
},
["cooldownTextDisabled"] = false,
["useCooldownModRate"] = true,
["width"] = 64,
["id"] = "ShieldIcon",
["alpha"] = 1,
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["zoom"] = 0,
["uid"] = "nD9E22TcLVu",
["inverse"] = false,
["authorOptions"] = {
},
["conditions"] = {
},
["information"] = {
},
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
},
["전문기술 - 응급치료"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"응급치료\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff32CD32%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_status"] = false,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["names"] = {
},
["use_class"] = false,
["use_unit"] = true,
["subeventPrefix"] = "SPELL",
["use_powertype"] = false,
["spellName"] = 3274,
["use_genericShowOn"] = true,
["type"] = "spell",
["use_count"] = true,
["subeventSuffix"] = "_CAST_START",
["debuffType"] = "HELPFUL",
["spellIds"] = {
},
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["unit"] = "player",
["talent"] = {
},
["classification"] = {
},
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["frameStrata"] = 1,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = false,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_text_format_p_time_precision"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["text_text_format_p_time_legacy_floor"] = false,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_format"] = 0,
["anchorXOffset"] = 0,
["type"] = "subtext",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_shadowXOffset"] = 1,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_fontType"] = "OUTLINE",
["anchorYOffset"] = 0,
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["text_text_format_p_time_dynamic_threshold"] = 60,
["text_text_format_c_format"] = "none",
},
},
["height"] = 35,
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["multiline"] = true,
["default"] = "",
["length"] = 10,
["name"] = "Macro",
["useLength"] = false,
},
},
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["use_zone"] = false,
["zoneIds"] = "",
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_exact_spellknown"] = false,
["use_spellknown"] = false,
["size"] = {
["multi"] = {
},
},
},
["desaturate"] = false,
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMax"] = "",
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 응급치료",
},
["icon"] = true,
["anchorFrameType"] = "SCREEN",
["alpha"] = 0.75,
["xOffset"] = 0,
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 응급치료",
["color"] = {
1,
1,
1,
1,
},
["useCooldownModRate"] = true,
["width"] = 35,
["internalVersion"] = 85,
["uid"] = "if2VQuJIQHE",
["inverse"] = true,
["progressSource"] = {
-1,
"",
},
["displayIcon"] = 133971,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["url"] = "",
},
["WarnShieldText"] = {
["outline"] = "OUTLINE",
["color"] = {
1,
0.3686274588108063,
0,
1,
},
["displayText"] = "신의 권능: 보호막으로 보호받고 있습니다!",
["shadowYOffset"] = -1,
["anchorPoint"] = "CENTER",
["displayText_format_p_time_format"] = 0,
["customTextUpdate"] = "event",
["automaticWidth"] = "Auto",
["actions"] = {
["start"] = {
["message_type"] = "WHISPER",
["do_message"] = false,
["message_dest"] = "",
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["rem"] = "0",
["auranames"] = {
"신의 권능: 보호막",
},
["names"] = {
},
["powertype"] = 1,
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
["showClones"] = false,
["useName"] = true,
["use_debuffClass"] = false,
["auraspellids"] = {
"27607",
"6788",
},
["event"] = "Power",
["use_unit"] = true,
["subeventPrefix"] = "SPELL",
["useExactSpellId"] = false,
["spellIds"] = {
},
["unit"] = "player",
["remOperator"] = ">=",
["subeventSuffix"] = "_CAST_START",
["type"] = "aura2",
["useRem"] = true,
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["class"] = "WARRIOR",
["use_requirePowerType"] = true,
["use_unit"] = true,
["use_class"] = false,
["powertype"] = 1,
["event"] = "Power",
["unit"] = "player",
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["displayText_format_p_format"] = "timed",
["internalVersion"] = 85,
["selfPoint"] = "BOTTOM",
["font"] = "Friz Quadrata TT",
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["load"] = {
["use_class"] = true,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["single"] = "WARRIOR",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["fontSize"] = 12,
["displayText_format_n_format"] = "none",
["shadowXOffset"] = 1,
["regionType"] = "text",
["xOffset"] = 0,
["displayText_format_1.casterName_format"] = "none",
["parent"] = "신의권능: 보호막 (전사)",
["displayText_format_p_time_precision"] = 1,
["conditions"] = {
},
["displayText_format_p_time_mod_rate"] = true,
["wordWrap"] = "WordWrap",
["justify"] = "LEFT",
["authorOptions"] = {
},
["id"] = "WarnShieldText",
["uid"] = "3ShGMvYuLI1",
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["yOffset"] = 0,
["config"] = {
},
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["displayText_format_p_time_legacy_floor"] = false,
["shadowColor"] = {
0,
0,
0,
1,
},
["fixedWidth"] = 200,
["information"] = {
},
["displayText_format_p_time_dynamic_threshold"] = 60,
},
["전문기술 - 요리"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"요리\"\n  local fireItem = GetItemCount(4470)\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cffFFD700%s(%s)|r \\n%s\\n(%s)\", proff, fireItem, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_status"] = false,
["use_threatvalue"] = false,
["use_genericShowOn"] = true,
["genericShowOn"] = "showAlways",
["subeventPrefix"] = "SPELL",
["use_class"] = false,
["use_unit"] = true,
["use_threatpct"] = false,
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["names"] = {
},
["classification"] = {
},
["use_count"] = true,
["subeventSuffix"] = "_CAST_START",
["unit"] = "player",
["spellIds"] = {
},
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["spellName"] = 3102,
["talent"] = {
},
["type"] = "spell",
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["frameStrata"] = 1,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glow"] = false,
["glowThickness"] = 1,
["useGlowColor"] = false,
["glowXOffset"] = 0,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["desaturate"] = false,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["use_spellknown"] = false,
["size"] = {
["multi"] = {
},
},
["use_zone"] = false,
["use_exact_spellknown"] = false,
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["zoneIds"] = "",
},
["xOffset"] = 0,
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["displayIcon"] = 133971,
["adjustedMax"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["default"] = "",
["name"] = "Macro",
["length"] = 10,
["multiline"] = true,
["useLength"] = false,
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["uid"] = "f1ctSTYPDGm",
["useTooltip"] = false,
["width"] = 35,
["alpha"] = 0.75,
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["preset"] = "alphaPulse",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["cooldownTextDisabled"] = false,
["zoom"] = 0,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 요리",
["url"] = "",
["useCooldownModRate"] = true,
["anchorFrameType"] = "SCREEN",
["actions"] = {
["start"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
["finish"] = {
},
},
["config"] = {
["macrotext"] = "/사용 요리\n/사용 작은 모닥불",
},
["inverse"] = true,
["color"] = {
1,
1,
1,
1,
},
["conditions"] = {
},
["cooldown"] = false,
["progressSource"] = {
-1,
"",
},
},
["신의권능: 보호막 (전사)"] = {
["grow"] = "DOWN",
["controlledChildren"] = {
"WarnShieldText",
"ShieldIcon",
},
["borderBackdrop"] = "Blizzard Tooltip",
["xOffset"] = 0,
["yOffset"] = 250.0000000000001,
["anchorPoint"] = "CENTER",
["borderColor"] = {
0,
0,
0,
1,
},
["space"] = 2,
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["names"] = {
},
["type"] = "aura2",
["spellIds"] = {
},
["subeventSuffix"] = "_CAST_START",
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["event"] = "Health",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
},
["columnSpace"] = 1,
["radius"] = 200,
["selfPoint"] = "TOP",
["align"] = "CENTER",
["stagger"] = 0,
["subRegions"] = {
},
["borderInset"] = 1,
["authorOptions"] = {
},
["load"] = {
["size"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
},
},
["talent"] = {
["multi"] = {
},
},
},
["limit"] = 5,
["backdropColor"] = {
1,
1,
1,
0.5,
},
["rotation"] = 0,
["animate"] = false,
["fullCircle"] = true,
["scale"] = 1,
["centerType"] = "LR",
["border"] = false,
["borderEdge"] = "Square Full White",
["regionType"] = "dynamicgroup",
["borderSize"] = 2,
["sort"] = "none",
["arcLength"] = 360,
["useLimit"] = false,
["constantFactor"] = "RADIUS",
["gridType"] = "RD",
["borderOffset"] = 4,
["rowSpace"] = 1,
["alpha"] = 1,
["id"] = "신의권능: 보호막 (전사)",
["gridWidth"] = 5,
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["stepAngle"] = 15,
["config"] = {
},
["uid"] = "7cYZ2iEhchb",
["internalVersion"] = 85,
["conditions"] = {
},
["information"] = {
},
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
},
["전문기술 - 대장기술"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"대장기술\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cffFF8C00%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["url"] = "",
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_count"] = true,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["subeventPrefix"] = "SPELL",
["use_class"] = false,
["use_unit"] = true,
["unit"] = "player",
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["names"] = {
},
["classification"] = {
},
["use_status"] = false,
["subeventSuffix"] = "_CAST_START",
["type"] = "spell",
["count"] = "0",
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["spellIds"] = {
},
["spellName"] = 2018,
["talent"] = {
},
["use_genericShowOn"] = true,
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["desc"] = "",
["alpha"] = 0.75,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = false,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["color"] = {
1,
1,
1,
1,
},
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_spellknown"] = false,
["zoneIds"] = "",
["spec"] = {
["multi"] = {
},
},
["use_exact_spellknown"] = false,
["use_zone"] = false,
["size"] = {
["multi"] = {
},
},
},
["icon"] = true,
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMax"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["name"] = "Macro",
["multiline"] = true,
["length"] = 10,
["default"] = "",
["useLength"] = false,
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 대장기술",
},
["desaturate"] = false,
["anchorFrameType"] = "SCREEN",
["frameStrata"] = 1,
["selfPoint"] = "CENTER",
["cooldownTextDisabled"] = false,
["zoom"] = 0,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 대장기술",
["xOffset"] = 0,
["useCooldownModRate"] = true,
["width"] = 35,
["internalVersion"] = 85,
["uid"] = "qxAFK38nEaB",
["inverse"] = true,
["cooldownEdge"] = true,
["displayIcon"] = 136241,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["progressSource"] = {
-1,
"",
},
},
["전문기술 - 연금술"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"연금술\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff00BFFF%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_status"] = false,
["use_threatvalue"] = false,
["use_genericShowOn"] = true,
["genericShowOn"] = "showAlways",
["use_unit"] = true,
["use_class"] = false,
["subeventPrefix"] = "SPELL",
["names"] = {
},
["use_powertype"] = false,
["spellName"] = 2259,
["unit"] = "player",
["classification"] = {
},
["use_count"] = true,
["talent"] = {
},
["type"] = "spell",
["spellIds"] = {
},
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["debuffType"] = "HELPFUL",
["subeventSuffix"] = "_CAST_START",
["use_threatpct"] = false,
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["color"] = {
1,
1,
1,
1,
},
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = false,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["desaturate"] = false,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_spellknown"] = false,
["zoneIds"] = "",
["spec"] = {
["multi"] = {
},
},
["use_exact_spellknown"] = false,
["use_zone"] = false,
["size"] = {
["multi"] = {
},
},
},
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["name"] = "Macro",
["multiline"] = true,
["length"] = 10,
["default"] = "",
["useLength"] = false,
},
},
["useAdjustededMax"] = false,
["url"] = "",
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMin"] = "",
["xOffset"] = 0,
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 연금술",
},
["progressSource"] = {
-1,
"",
},
["anchorFrameType"] = "SCREEN",
["alpha"] = 0.75,
["frameStrata"] = 1,
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 연금술",
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["useCooldownModRate"] = true,
["width"] = 35,
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["uid"] = "ko(lkhdmPTZ",
["inverse"] = true,
["useTooltip"] = false,
["displayIcon"] = 136240,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["adjustedMax"] = "",
},
["전문기술 바"] = {
["arcLength"] = 360,
["controlledChildren"] = {
"전문기술 - 응급치료",
"전문기술 - 요리",
"전문기술 - 낚시",
"전문기술 - 무두질",
"전문기술 - 연금술",
"전문기술 - 약초채집",
"전문기술 - 재봉술",
"전문기술 - 마법부여",
"전문기술 - 대장기술",
"전문기술 - 기계공학",
"전문기술 - 가죽세공",
"전문기술 - 제련술",
},
["borderBackdrop"] = "Blizzard Tooltip",
["xOffset"] = -10,
["preferToUpdate"] = false,
["yOffset"] = 50,
["anchorPoint"] = "BOTTOMRIGHT",
["borderColor"] = {
0,
0,
0,
1,
},
["space"] = 2,
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["unit"] = "player",
["type"] = "aura2",
["spellIds"] = {
},
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["subeventPrefix"] = "SPELL",
["event"] = "Health",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
},
["columnSpace"] = 1,
["radius"] = 200,
["useLimit"] = false,
["align"] = "CENTER",
["alpha"] = 1,
["stagger"] = 0,
["internalVersion"] = 85,
["gridType"] = "LU",
["subRegions"] = {
},
["authorOptions"] = {
},
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["load"] = {
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["grow"] = "GRID",
["backdropColor"] = {
1,
1,
1,
0.5,
},
["selfPoint"] = "BOTTOMRIGHT",
["source"] = "import",
["rotation"] = 0,
["scale"] = 0.8500000000000001,
["centerType"] = "LR",
["border"] = false,
["borderEdge"] = "Square Full White",
["stepAngle"] = 15,
["borderSize"] = 2,
["limit"] = 5,
["config"] = {
},
["sort"] = "none",
["constantFactor"] = "RADIUS",
["gridWidth"] = 10,
["borderOffset"] = 4,
["rowSpace"] = 1,
["tocversion"] = 30400,
["id"] = "전문기술 바",
["uid"] = "u(cpkSbfjFj",
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["regionType"] = "dynamicgroup",
["borderInset"] = 1,
["animate"] = false,
["fullCircle"] = true,
["conditions"] = {
},
["information"] = {
["forceEvents"] = true,
},
["sortHybridTable"] = {
["전문기술 - 응급치료"] = false,
["전문기술 - 가죽세공"] = false,
["전문기술 - 기계공학"] = false,
["전문기술 - 요리"] = false,
["전문기술 - 제련술"] = false,
["전문기술 - 대장기술"] = false,
["전문기술 - 재봉술"] = false,
["전문기술 - 연금술"] = false,
["전문기술 - 마법부여"] = false,
},
},
["전문기술 - 낚시"] = {
["iconSource"] = -1,
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["name"] = "Macro",
["multiline"] = true,
["length"] = 10,
["default"] = "",
["useLength"] = false,
},
},
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"낚시\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff00BFFF%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_count"] = true,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["use_unit"] = true,
["use_class"] = false,
["names"] = {
},
["subeventPrefix"] = "SPELL",
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["type"] = "spell",
["classification"] = {
},
["talent"] = {
},
["subeventSuffix"] = "_CAST_START",
["spellName"] = 18248,
["count"] = "0",
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["spellIds"] = {
},
["unit"] = "player",
["use_status"] = false,
["use_genericShowOn"] = true,
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["debuffType"] = "HELPFUL",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["useCooldownModRate"] = true,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["useGlowColor"] = false,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glow"] = false,
["glowScale"] = 1,
["glowDuration"] = 1,
["glowXOffset"] = 0,
["glowThickness"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_text_format_p_time_format"] = 0,
["text_text"] = "%c",
["text_text_format_p_time_mod_rate"] = true,
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["text_text_format_c_format"] = "none",
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_shadowXOffset"] = 1,
["anchorXOffset"] = 0,
["type"] = "subtext",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_format"] = "timed",
["text_shadowYOffset"] = 1,
["text_text_format_p_time_precision"] = 1,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_fontType"] = "OUTLINE",
["text_text_format_p_time_legacy_floor"] = false,
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["text_text_format_p_time_dynamic_threshold"] = 60,
["anchorYOffset"] = 0,
},
},
["height"] = 35,
["xOffset"] = 0,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_spellknown"] = false,
["zoneIds"] = "",
["spec"] = {
["multi"] = {
},
},
["use_exact_spellknown"] = false,
["use_zone"] = false,
["size"] = {
["multi"] = {
},
},
},
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMax"] = "",
["parent"] = "전문기술 바",
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 낚시",
},
["color"] = {
1,
1,
1,
1,
},
["anchorFrameType"] = "SCREEN",
["frameStrata"] = 1,
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["cooldownTextDisabled"] = false,
["zoom"] = 0,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 낚시",
["desaturate"] = false,
["alpha"] = 0.75,
["width"] = 35,
["url"] = "",
["uid"] = "NYK8EeOJ0Em",
["inverse"] = true,
["progressSource"] = {
-1,
"",
},
["displayIcon"] = 136245,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["useTooltip"] = false,
},
["전문기술 - 가죽세공"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"가죽 세공\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cffDEB887%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_count"] = true,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["use_unit"] = true,
["use_class"] = false,
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["names"] = {
},
["use_powertype"] = false,
["spellName"] = 2108,
["use_status"] = false,
["classification"] = {
},
["subeventSuffix"] = "_CAST_START",
["talent"] = {
},
["spellIds"] = {
},
["use_itemName"] = true,
["event"] = "Spell Known",
["use_exact_spellName"] = false,
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["use_genericShowOn"] = true,
["type"] = "spell",
["debuffType"] = "HELPFUL",
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["useCooldownModRate"] = true,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glow"] = false,
["glowThickness"] = 1,
["useGlowColor"] = false,
["glowXOffset"] = 0,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["preset"] = "alphaPulse",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_zone"] = false,
["size"] = {
["multi"] = {
},
},
["use_spellknown"] = false,
["use_exact_spellknown"] = false,
["spec"] = {
["multi"] = {
},
},
["zoneIds"] = "",
},
["actions"] = {
["start"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
["finish"] = {
},
},
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["displayIcon"] = "133611",
["adjustedMax"] = "",
["color"] = {
1,
1,
1,
1,
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["uid"] = "rubG2fQ6qrt",
["desaturate"] = false,
["width"] = 35,
["alpha"] = 0.75,
["xOffset"] = 0,
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 가죽세공",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["multiline"] = true,
["default"] = "",
["length"] = 10,
["name"] = "Macro",
["useLength"] = false,
},
},
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["internalVersion"] = 85,
["config"] = {
["macrotext"] = "/사용 가죽세공",
},
["inverse"] = true,
["progressSource"] = {
-1,
"",
},
["conditions"] = {
},
["cooldown"] = false,
["url"] = "",
},
["전문기술 - 무두질"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"무두질\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff00BFFF%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_status"] = false,
["use_threatvalue"] = false,
["use_genericShowOn"] = true,
["genericShowOn"] = "showAlways",
["subeventPrefix"] = "SPELL",
["use_class"] = false,
["names"] = {
},
["use_unit"] = true,
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["use_threatpct"] = false,
["type"] = "spell",
["use_count"] = true,
["talent"] = {
},
["unit"] = "player",
["spellIds"] = {
},
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["spellName"] = 13697,
["subeventSuffix"] = "_CAST_START",
["classification"] = {
},
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["alpha"] = 0.75,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glow"] = false,
["glowThickness"] = 1,
["useGlowColor"] = false,
["glowXOffset"] = 0,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_fontType"] = "OUTLINE",
["text_text_format_p_time_legacy_floor"] = false,
["text_visible"] = true,
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["internalVersion"] = 85,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["use_spellknown"] = false,
["size"] = {
["multi"] = {
},
},
["use_zone"] = false,
["use_exact_spellknown"] = false,
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["zoneIds"] = "",
},
["desaturate"] = false,
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["displayIcon"] = 136235,
["adjustedMax"] = "",
["url"] = "",
["useAdjustededMin"] = false,
["regionType"] = "icon",
["uid"] = "B(7peXWPdf5",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["default"] = "",
["name"] = "Macro",
["length"] = 10,
["multiline"] = true,
["useLength"] = false,
},
},
["width"] = 35,
["frameStrata"] = 1,
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["preset"] = "alphaPulse",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 무두질",
["color"] = {
1,
1,
1,
1,
},
["useCooldownModRate"] = true,
["anchorFrameType"] = "SCREEN",
["actions"] = {
["start"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
["finish"] = {
},
},
["config"] = {
["macrotext"] = "",
},
["inverse"] = true,
["xOffset"] = 0,
["conditions"] = {
},
["cooldown"] = false,
["progressSource"] = {
-1,
"",
},
},
["현재 타격무기"] = {
["iconSource"] = -1,
["color"] = {
1,
1,
1,
1,
},
["adjustedMax"] = "",
["adjustedMin"] = "",
["yOffset"] = 125,
["anchorPoint"] = "BOTTOM",
["cooldownSwipe"] = true,
["cooldownEdge"] = false,
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["useName"] = true,
["subeventSuffix"] = "_CAST_START",
["event"] = "Health",
["unit"] = "player",
["spellIds"] = {
},
["names"] = {
},
["auranames"] = {
"무장 해제",
},
["type"] = "aura2",
["subeventPrefix"] = "SPELL",
["debuffType"] = "HARMFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["itemName"] = 0,
["itemTypeName"] = {
["multi"] = {
[516] = true,
[527] = true,
[519] = true,
[1030] = true,
[512] = true,
},
},
["use_genericShowOn"] = true,
["genericShowOn"] = "showOnCooldown",
["use_unit"] = true,
["debuffType"] = "HELPFUL",
["type"] = "item",
["use_itemTypeName"] = false,
["subeventSuffix"] = "_CAST_START",
["use_equipped"] = true,
["use_itemName"] = true,
["use_itemSetId"] = true,
["spellIds"] = {
},
["names"] = {
},
["subeventPrefix"] = "SPELL",
["event"] = "Item Type Equipped",
["unit"] = "player",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "item",
["use_itemTypeName"] = false,
["itemTypeName"] = {
["multi"] = {
[518] = true,
[517] = true,
[513] = true,
[520] = true,
},
},
["use_genericShowOn"] = true,
["event"] = "Item Type Equipped",
["unit"] = "player",
["genericShowOn"] = "showOnCooldown",
["use_unit"] = true,
["itemName"] = 0,
["use_itemName"] = true,
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["itemName"] = 0,
["use_itemTypeName"] = false,
["itemTypeName"] = {
["multi"] = {
[532] = true,
},
},
["use_genericShowOn"] = true,
["event"] = "Item Type Equipped",
["unit"] = "player",
["genericShowOn"] = "showOnCooldown",
["use_itemName"] = true,
["type"] = "item",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["text_shadowXOffset"] = 0,
["text_text_format_s_format"] = "none",
["text_text"] = "%n",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["type"] = "subtext",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "Friz Quadrata TT",
["text_shadowYOffset"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_n_format"] = "none",
["anchor_point"] = "OUTER_TOP",
["text_fontSize"] = 11,
["anchorXOffset"] = 0,
["text_fontType"] = "OUTLINE",
},
{
["glowFrequency"] = 0.25,
["type"] = "subglow",
["useGlowColor"] = false,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowScale"] = 1,
["glowThickness"] = 1,
["glowDuration"] = 1,
["glowXOffset"] = 0,
["glow"] = false,
["glowLines"] = 8,
["glowBorder"] = false,
},
},
["height"] = 30,
["load"] = {
["use_class"] = true,
["use_itemtypeequipped"] = false,
["talent"] = {
["multi"] = {
},
},
["itemtypeequipped"] = {
["multi"] = {
[520] = true,
[513] = true,
[517] = true,
[519] = true,
[1030] = true,
[527] = true,
[532] = true,
[516] = true,
[512] = true,
},
},
["class"] = {
["single"] = "WARRIOR",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["useAdjustededMax"] = false,
["useAdjustededMin"] = false,
["regionType"] = "icon",
["cooldown"] = true,
["xOffset"] = 75,
["authorOptions"] = {
},
["progressSource"] = {
-1,
"",
},
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["cooldownTextDisabled"] = false,
["alpha"] = 1,
["config"] = {
},
["id"] = "현재 타격무기",
["useCooldownModRate"] = true,
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["width"] = 30,
["uid"] = "wFDdeJP4Wj3",
["inverse"] = false,
["zoom"] = 0,
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["variable"] = "show",
["value"] = 1,
},
["linked"] = false,
["changes"] = {
{
["value"] = 132343,
["property"] = "displayIcon",
},
{
["value"] = "무장 없음",
["property"] = "sub.2.text_text",
},
{
["value"] = {
1,
0.3333333432674408,
0,
1,
},
["property"] = "sub.2.text_color",
},
},
},
{
["check"] = {
["trigger"] = 2,
["variable"] = "show",
["value"] = 1,
},
["linked"] = true,
["changes"] = {
{
["value"] = 132341,
["property"] = "displayIcon",
},
{
["value"] = "한손 무기",
["property"] = "sub.2.text_text",
},
{
["property"] = "sub.2.text_color",
},
},
},
{
["check"] = {
["trigger"] = 3,
["variable"] = "show",
["value"] = 1,
},
["linked"] = true,
["changes"] = {
{
["value"] = 132349,
["property"] = "displayIcon",
},
{
["value"] = "양손 무기",
["property"] = "sub.2.text_text",
},
{
["property"] = "sub.2.text_color",
},
},
},
{
["check"] = {
["trigger"] = 4,
["variable"] = "show",
["value"] = 1,
},
["linked"] = true,
["changes"] = {
{
["value"] = "136245",
["property"] = "displayIcon",
},
{
["value"] = "낚시",
["property"] = "sub.2.text_text",
},
{
["property"] = "sub.2.text_color",
},
},
},
},
["information"] = {
},
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
},
["전문기술 - 제련술"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"채광\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff808000%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["url"] = "",
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_count"] = true,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["use_unit"] = true,
["use_class"] = false,
["unit"] = "player",
["names"] = {
},
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["subeventPrefix"] = "SPELL",
["type"] = "spell",
["use_status"] = false,
["talent"] = {
},
["classification"] = {
},
["count"] = "0",
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["spellIds"] = {
},
["spellName"] = 2656,
["subeventSuffix"] = "_CAST_START",
["use_genericShowOn"] = true,
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["color"] = {
1,
1,
1,
1,
},
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = false,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["cooldownEdge"] = true,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["use_zone"] = false,
["zoneIds"] = "",
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_exact_spellknown"] = false,
["use_spellknown"] = false,
["size"] = {
["multi"] = {
},
},
},
["desaturate"] = false,
["useAdjustededMax"] = false,
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMin"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["multiline"] = true,
["default"] = "",
["length"] = 10,
["name"] = "Macro",
["useLength"] = false,
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 제련술\n/사용 광물 찾기",
},
["progressSource"] = {
-1,
"",
},
["anchorFrameType"] = "SCREEN",
["useCooldownModRate"] = true,
["frameStrata"] = 1,
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 제련술",
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["alpha"] = 0.75,
["width"] = 35,
["useTooltip"] = false,
["uid"] = "YPcbfNoSrhf",
["inverse"] = true,
["xOffset"] = 0,
["displayIcon"] = 133971,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["adjustedMax"] = "",
},
["탄환 및 화살"] = {
["iconSource"] = -1,
["authorOptions"] = {
},
["preferToUpdate"] = false,
["adjustedMin"] = "",
["yOffset"] = 125,
["anchorPoint"] = "BOTTOM",
["cooldownSwipe"] = true,
["cooldownEdge"] = false,
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["itemName"] = 0,
["itemTypeName"] = {
},
["use_genericShowOn"] = true,
["genericShowOn"] = "showAlways",
["use_unit"] = true,
["use_showgcd"] = false,
["itemSlot"] = 0,
["debuffType"] = "HELPFUL",
["type"] = "item",
["subeventSuffix"] = "_CAST_START",
["use_remaining"] = false,
["use_itemName"] = true,
["duration"] = "1",
["use_itemSlot"] = true,
["unit"] = "player",
["spellIds"] = {
},
["use_testForCooldown"] = true,
["names"] = {
},
["event"] = "Cooldown Progress (Equipment Slot)",
["unevent"] = "auto",
["subeventPrefix"] = "SPELL",
},
["untrigger"] = {
["genericShowOn"] = "showAlways",
["itemSlot"] = 17,
},
},
{
["trigger"] = {
["itemName"] = 0,
["use_genericShowOn"] = true,
["event"] = "Cooldown Progress (Equipment Slot)",
["unit"] = "player",
["use_itemSlot"] = true,
["itemSlot"] = 18,
["use_testForCooldown"] = false,
["use_itemName"] = true,
["type"] = "item",
["genericShowOn"] = "showAlways",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["text_shadowXOffset"] = 0,
["text_text"] = "%n",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["type"] = "subtext",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "Friz Quadrata TT",
["text_shadowYOffset"] = 0,
["text_wordWrap"] = "WordWrap",
["text_fontType"] = "OUTLINE",
["text_text_format_n_format"] = "none",
["anchor_point"] = "OUTER_TOP",
["text_fontSize"] = 11,
["anchorXOffset"] = 0,
["text_visible"] = true,
},
{
["glowFrequency"] = 0.5,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 20,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = true,
["glowScale"] = 1,
["glowLines"] = 1,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 0,
["text_text_format_s_format"] = "none",
["text_text"] = "%s",
["text_text_format_p_format"] = "timed",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["text_text_format_t_time_format"] = 0,
["anchorYOffset"] = 0,
["text_justify"] = "RIGHT",
["rotateText"] = "NONE",
["text_text_format_t_format"] = "timed",
["text_text_format_t_time_dynamic_threshold"] = 60,
["text_text_format_t_time_legacy_floor"] = false,
["type"] = "subtext",
["text_text_format_t_time_precision"] = 1,
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "Friz Quadrata TT",
["anchorXOffset"] = 0,
["text_shadowYOffset"] = 0,
["text_text_format_t_time_mod_rate"] = true,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_fontType"] = "OUTLINE",
["text_text_format_p_time_format"] = 0,
["anchor_point"] = "INNER_BOTTOM",
["text_fontSize"] = 12,
["text_text_format_p_time_dynamic_threshold"] = 60,
["text_text_format_p_time_precision"] = 1,
},
},
["height"] = 30,
["load"] = {
["use_class"] = false,
["use_itemtypeequipped"] = false,
["itemtypeequipped"] = {
["single"] = 514,
["multi"] = {
[515] = true,
[514] = true,
[528] = true,
},
},
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "HUNTER",
["multi"] = {
["HUNTER"] = true,
["WARRIOR"] = true,
["ROGUE"] = true,
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["useAdjustededMax"] = false,
["source"] = "import",
["cooldownTextDisabled"] = false,
["color"] = {
1,
1,
1,
1,
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["animation"] = {
["start"] = {
["type"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["easeType"] = "none",
},
},
["icon"] = true,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["xOffset"] = 0,
["uid"] = "dzBgBX)0hvc",
["frameStrata"] = 1,
["zoom"] = 0,
["auto"] = true,
["tocversion"] = 20502,
["id"] = "탄환 및 화살",
["width"] = 30,
["useCooldownModRate"] = true,
["anchorFrameType"] = "SCREEN",
["alpha"] = 1,
["config"] = {
},
["inverse"] = false,
["progressSource"] = {
-1,
"",
},
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["variable"] = "stacks",
["value"] = "200",
["op"] = ">",
},
["linked"] = false,
["changes"] = {
{
["value"] = "*",
["property"] = "sub.4.text_text",
},
},
},
{
["check"] = {
["trigger"] = 1,
["op"] = "<=",
["variable"] = "stacks",
["value"] = "200",
},
["linked"] = true,
["changes"] = {
{
["value"] = "%s",
["property"] = "sub.4.text_text",
},
},
},
{
["check"] = {
["trigger"] = -2,
["variable"] = "OR",
["op"] = ">=",
["checks"] = {
{
["trigger"] = 1,
["variable"] = "stacks",
["value"] = "100",
["op"] = ">=",
},
{
["trigger"] = 2,
["variable"] = "stacks",
["value"] = "100",
["op"] = ">=",
},
},
},
["changes"] = {
{
["property"] = "sub.4.text_color",
},
},
},
{
["check"] = {
["trigger"] = -2,
["variable"] = "AND",
["checks"] = {
{
["trigger"] = -2,
["variable"] = "OR",
["op"] = "<",
["checks"] = {
{
["trigger"] = 1,
["variable"] = "stacks",
["value"] = "100",
["op"] = "<",
},
{
["trigger"] = 2,
["variable"] = "stacks",
["value"] = "100",
["op"] = "<",
},
},
},
{
["trigger"] = -2,
["variable"] = "OR",
["op"] = ">=",
["checks"] = {
{
["trigger"] = 1,
["op"] = ">=",
["variable"] = "stacks",
["value"] = "50",
},
{
["trigger"] = 2,
["variable"] = "stacks",
["value"] = "50",
["op"] = ">=",
},
},
},
},
},
["linked"] = true,
["changes"] = {
{
["value"] = {
1,
0.4313725829124451,
0,
1,
},
["property"] = "sub.4.text_color",
},
},
},
{
["check"] = {
["trigger"] = -2,
["op"] = "<",
["variable"] = "AND",
["checks"] = {
{
["trigger"] = -2,
["op"] = "<",
["variable"] = "OR",
["checks"] = {
{
["trigger"] = 1,
["op"] = "<",
["variable"] = "stacks",
["value"] = "50",
},
{
["trigger"] = 2,
["variable"] = "stacks",
["value"] = "50",
["op"] = "<",
},
},
},
{
["trigger"] = -2,
["op"] = ">=",
["variable"] = "OR",
["checks"] = {
{
["trigger"] = 1,
["variable"] = "stacks",
["value"] = "0",
["op"] = ">=",
},
{
["trigger"] = 2,
["variable"] = "stacks",
["value"] = "0",
["op"] = ">=",
},
},
},
},
},
["linked"] = true,
["changes"] = {
{
["value"] = {
1,
0.1764705926179886,
0.2039215862751007,
1,
},
["property"] = "sub.4.text_color",
},
},
},
},
["cooldown"] = false,
["adjustedMax"] = "",
},
["전문기술 - 기계공학"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"기계공학\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff2F4F4F%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["url"] = "",
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_count"] = true,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["subeventPrefix"] = "SPELL",
["use_class"] = false,
["use_unit"] = true,
["spellName"] = 4036,
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["names"] = {
},
["type"] = "spell",
["use_status"] = false,
["subeventSuffix"] = "_CAST_START",
["use_genericShowOn"] = true,
["spellIds"] = {
},
["use_itemName"] = true,
["unit"] = "player",
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["event"] = "Spell Known",
["talent"] = {
},
["classification"] = {
},
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["desc"] = "",
["alpha"] = 0.75,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = false,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["color"] = {
1,
1,
1,
1,
},
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_spellknown"] = false,
["zoneIds"] = "",
["spec"] = {
["multi"] = {
},
},
["use_exact_spellknown"] = false,
["use_zone"] = false,
["size"] = {
["multi"] = {
},
},
},
["icon"] = true,
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMax"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["name"] = "Macro",
["multiline"] = true,
["length"] = 10,
["default"] = "",
["useLength"] = false,
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 기계공학",
},
["desaturate"] = false,
["anchorFrameType"] = "SCREEN",
["frameStrata"] = 1,
["selfPoint"] = "CENTER",
["cooldownTextDisabled"] = false,
["zoom"] = 0,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 기계공학",
["xOffset"] = 0,
["useCooldownModRate"] = true,
["width"] = 35,
["internalVersion"] = 85,
["uid"] = "933fLZM0J)w",
["inverse"] = true,
["cooldownEdge"] = true,
["displayIcon"] = 134520,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["progressSource"] = {
-1,
"",
},
},
["전문기술 - 약초채집"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"약초 채집\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff00BFFF%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["url"] = "",
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_status"] = false,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["names"] = {
},
["use_class"] = false,
["subeventPrefix"] = "SPELL",
["use_unit"] = true,
["use_powertype"] = false,
["spellName"] = 2383,
["use_genericShowOn"] = true,
["classification"] = {
},
["talent"] = {
},
["subeventSuffix"] = "_CAST_START",
["debuffType"] = "HELPFUL",
["count"] = "0",
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["spellIds"] = {
},
["type"] = "spell",
["use_count"] = true,
["unit"] = "player",
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["debuffType"] = "HELPFUL",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 85,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["preset"] = "alphaPulse",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowXOffset"] = 0,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glowScale"] = 1,
["glowDuration"] = 1,
["useGlowColor"] = false,
["glow"] = false,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_text_format_p_time_precision"] = 1,
["text_text"] = "%c",
["text_shadowColor"] = {
0,
0,
0,
1,
},
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_format"] = 0,
["anchorXOffset"] = 0,
["type"] = "subtext",
["text_text_format_p_time_mod_rate"] = true,
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_format"] = "timed",
["text_shadowYOffset"] = 1,
["text_shadowXOffset"] = 1,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_fontType"] = "OUTLINE",
["text_text_format_p_time_legacy_floor"] = false,
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["text_text_format_p_time_dynamic_threshold"] = 60,
["text_text_format_c_format"] = "none",
},
},
["height"] = 35,
["xOffset"] = 0,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["use_spellknown"] = false,
["size"] = {
["multi"] = {
},
},
["use_zone"] = false,
["use_exact_spellknown"] = false,
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["zoneIds"] = "",
},
["cooldownEdge"] = true,
["useAdjustededMax"] = false,
["actions"] = {
["start"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
["finish"] = {
},
},
["source"] = "import",
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["displayIcon"] = 136240,
["adjustedMin"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["default"] = "",
["name"] = "Macro",
["length"] = 10,
["multiline"] = true,
["useLength"] = false,
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["uid"] = "1RjnwANXRaM",
["progressSource"] = {
-1,
"",
},
["width"] = 35,
["useCooldownModRate"] = true,
["frameStrata"] = 1,
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 약초채집",
["useTooltip"] = false,
["alpha"] = 0.75,
["anchorFrameType"] = "SCREEN",
["color"] = {
1,
1,
1,
1,
},
["config"] = {
["macrotext"] = "/사용 약초 찾기",
},
["inverse"] = true,
["desaturate"] = false,
["conditions"] = {
},
["cooldown"] = false,
["adjustedMax"] = "",
},
["전문기술 - 마법부여"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"마법부여\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cffB22222%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["url"] = "",
["icon"] = true,
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_count"] = true,
["use_threatvalue"] = false,
["use_threatpct"] = false,
["genericShowOn"] = "showAlways",
["use_unit"] = true,
["use_class"] = false,
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["names"] = {
},
["classification"] = {
},
["use_status"] = false,
["talent"] = {
},
["subeventSuffix"] = "_CAST_START",
["spellIds"] = {
},
["use_itemName"] = true,
["event"] = "Spell Known",
["realSpellName"] = "요리",
["use_spellName"] = true,
["count"] = "0",
["spellName"] = 7412,
["use_genericShowOn"] = true,
["type"] = "spell",
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["easeStrength"] = 3,
["preset"] = "alphaPulse",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["desc"] = "",
["useCooldownModRate"] = true,
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glow"] = false,
["glowThickness"] = 1,
["useGlowColor"] = false,
["glowXOffset"] = 0,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["xOffset"] = 0,
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_zone"] = false,
["size"] = {
["multi"] = {
},
},
["use_spellknown"] = false,
["use_exact_spellknown"] = false,
["spec"] = {
["multi"] = {
},
},
["zoneIds"] = "",
},
["actions"] = {
["start"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
["finish"] = {
},
},
["useAdjustededMax"] = false,
["adjustedMin"] = "",
["source"] = "import",
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["displayIcon"] = "136244",
["adjustedMax"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["multiline"] = true,
["default"] = "",
["length"] = 10,
["name"] = "Macro",
["useLength"] = false,
},
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["uid"] = "xyDO1czXCxR",
["selfPoint"] = "CENTER",
["width"] = 35,
["frameStrata"] = 1,
["desaturate"] = false,
["zoom"] = 0,
["cooldownTextDisabled"] = false,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 마법부여",
["color"] = {
1,
1,
1,
1,
},
["alpha"] = 0.75,
["anchorFrameType"] = "SCREEN",
["internalVersion"] = 85,
["config"] = {
["macrotext"] = "/사용 마법부여",
},
["inverse"] = true,
["progressSource"] = {
-1,
"",
},
["conditions"] = {
},
["cooldown"] = false,
["cooldownEdge"] = true,
},
["전문기술 - 재봉술"] = {
["iconSource"] = -1,
["parent"] = "전문기술 바",
["preferToUpdate"] = false,
["customText"] = "function()\n  local proff = \"재봉술\"\n  \n  for i = 1, GetNumSkillLines() do\n    local skillName, isHeader, isExpanded, skillRank, numTempPoints, skillModifier,\n    skillMaxRank, isAbandonable, stepCost, rankCost, minLevel, skillCostType,\n    skillDescription = GetSkillLineInfo(i)\n    if skillName == proff then\n      return (string.format(\"\\n|cff4682B4%s|r \\n%s\\n(%s)\", proff, skillRank, skillMaxRank))\n    end\n  end\nend",
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["cooldownSwipe"] = true,
["customTextUpdate"] = "update",
["cooldownEdge"] = true,
["actions"] = {
["start"] = {
},
["finish"] = {
},
["init"] = {
["custom"] = "local self = aura_env\nif self.frame then\n    self.frame:Hide()\n    self.frame:SetParent(nil)\nend\n\nself.frame = CreateFrame('Button', WeakAuras.GenerateUniqueID(), self.region, 'SecureActionButtonTemplate')\nself.frame:SetAllPoints()\n\nself.frame:SetAttribute(\"type1\", \"macro\")\nself.frame:SetAttribute(\"macrotext\", self.config['macrotext'])",
["do_custom"] = true,
},
},
["triggers"] = {
{
["trigger"] = {
["itemName"] = 47499,
["use_status"] = false,
["use_threatvalue"] = false,
["use_genericShowOn"] = true,
["genericShowOn"] = "showAlways",
["subeventPrefix"] = "SPELL",
["use_class"] = false,
["names"] = {
},
["spellName"] = 3909,
["use_powertype"] = false,
["debuffType"] = "HELPFUL",
["use_threatpct"] = false,
["classification"] = {
},
["use_count"] = true,
["subeventSuffix"] = "_CAST_START",
["talent"] = {
},
["count"] = "0",
["event"] = "Spell Known",
["unit"] = "player",
["realSpellName"] = "요리",
["use_spellName"] = true,
["spellIds"] = {
},
["use_itemName"] = true,
["type"] = "spell",
["use_unit"] = true,
["use_track"] = true,
["count_operator"] = ">",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_incombat"] = false,
["unit"] = "player",
["use_unit"] = true,
["use_alive"] = true,
["event"] = "Conditions",
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["useTooltip"] = false,
["keepAspectRatio"] = false,
["selfPoint"] = "CENTER",
["desc"] = "",
["authorOptions"] = {
{
["type"] = "input",
["useDesc"] = false,
["width"] = 1,
["key"] = "macrotext",
["default"] = "",
["name"] = "Macro",
["length"] = 10,
["multiline"] = true,
["useLength"] = false,
},
},
["version"] = 2,
["subRegions"] = {
{
["type"] = "subbackground",
},
{
["glowFrequency"] = 0.1,
["type"] = "subglow",
["glowDuration"] = 1,
["glowType"] = "buttonOverlay",
["glowLength"] = 10,
["glowYOffset"] = 0,
["glowColor"] = {
1,
1,
1,
1,
},
["glowThickness"] = 1,
["glow"] = false,
["glowXOffset"] = 0,
["useGlowColor"] = false,
["glowScale"] = 1,
["glowLines"] = 8,
["glowBorder"] = false,
},
{
["text_shadowXOffset"] = 1,
["text_text"] = "%c",
["text_text_format_p_format"] = "timed",
["text_selfPoint"] = "AUTO",
["text_automaticWidth"] = "Auto",
["text_fixedWidth"] = 64,
["anchorYOffset"] = 0,
["text_justify"] = "CENTER",
["rotateText"] = "NONE",
["text_text_format_p_time_precision"] = 1,
["text_text_format_p_time_dynamic_threshold"] = 60,
["type"] = "subtext",
["text_text_format_c_format"] = "none",
["text_color"] = {
1,
1,
1,
1,
},
["text_font"] = "[WoW] 기본 글꼴",
["text_text_format_p_time_mod_rate"] = true,
["text_shadowYOffset"] = 1,
["text_text_format_p_time_format"] = 0,
["text_wordWrap"] = "WordWrap",
["text_visible"] = true,
["text_text_format_p_time_legacy_floor"] = false,
["text_fontType"] = "OUTLINE",
["anchor_point"] = "CENTER",
["text_fontSize"] = 10,
["anchorXOffset"] = 0,
["text_shadowColor"] = {
0,
0,
0,
1,
},
},
},
["height"] = 35,
["animation"] = {
["start"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeType"] = "none",
["duration_type"] = "seconds",
["preset"] = "alphaPulse",
["easeStrength"] = 3,
},
["finish"] = {
["easeStrength"] = 3,
["type"] = "none",
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["load"] = {
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["use_zone"] = false,
["zoneIds"] = "",
["class"] = {
["multi"] = {
["PRIEST"] = true,
},
},
["use_exact_spellknown"] = false,
["use_spellknown"] = false,
["size"] = {
["multi"] = {
},
},
},
["icon"] = true,
["useAdjustededMax"] = false,
["url"] = "",
["source"] = "import",
["cooldown"] = false,
["conditions"] = {
},
["adjustedMin"] = "",
["color"] = {
1,
1,
1,
1,
},
["useAdjustededMin"] = false,
["regionType"] = "icon",
["config"] = {
["macrotext"] = "/사용 재봉술",
},
["progressSource"] = {
-1,
"",
},
["anchorFrameType"] = "SCREEN",
["alpha"] = 0.75,
["frameStrata"] = 1,
["cooldownTextDisabled"] = false,
["zoom"] = 0,
["semver"] = "1.0.1",
["tocversion"] = 30400,
["id"] = "전문기술 - 재봉술",
["internalVersion"] = 85,
["useCooldownModRate"] = true,
["width"] = 35,
["xOffset"] = 0,
["uid"] = "T1PJZiCuEaR",
["inverse"] = true,
["desaturate"] = false,
["displayIcon"] = 136249,
["information"] = {
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["adjustedMax"] = "",
},
},
["lastUpgrade"] = 1755696923,
["editor_theme"] = "Monokai",
}
